version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5445:5432
    networks:
      - blog-project-network
  redis:
    image: redis:latest
    ports:
      - 6336:6379
    networks:
      - blog-project-network

  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env.docker
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - blog-project-network

networks:
  blog-project-network:
    driver: bridge

volumes:
  postgres_data: